<?php

namespace App\Support;

class MockChatData
{
    public static function isEnabled(): bool
    {
        return app()->environment(['local']);
    }

    public static function chatListProps(): array
    {
        return [
            'search' => '',
            'category' => 'whatsapp',
            'selected_contact' => '',
            'filter_id' => null,
            'counts' => self::counts(),
            'contact_list' => self::contactList(),
            'account_list' => self::accountList(),
            'sessions' => self::sessionMap(),
            'templates' => self::templates(),
            'products' => self::products(),
            'interactiveMessages' => self::interactiveMessages(),
            'mock_messages' => self::mockMessages(),
        ];
    }

    public static function hasContact(int $contactId): bool
    {
        return array_key_exists("contact_id_{$contactId}", self::contactList());
    }

    public static function messageListForContact(int $contactId): array
    {
        $messages = self::mockMessages();
        return $messages[$contactId] ?? [];
    }

    public static function counts(): array
    {
        return [
            'unread' => 15,
            'all' => 51,
            'archived' => 4,
        ];
    }

    public static function accountList(): array
    {
        return [
            1 => 'ONE TECH',
        ];
    }

    public static function contactList(): array
    {
        return [
            'contact_id_1' => [
                'id' => 1,
                'name' => 'Giulia Rossi',
                'number' => '+39 347 123 4567',
                'channel' => 'whatsapp',
                'insta_id' => 'giulia.rossi',
                'fb_id' => 'giulia.rossi',
            ],
            'contact_id_2' => [
                'id' => 2,
                'name' => 'Marco Bianchi',
                'number' => '+39 320 555 0199',
                'channel' => 'whatsapp',
                'insta_id' => 'marco_bianchi',
                'fb_id' => 'marco.bianchi',
            ],
            'contact_id_3' => [
                'id' => 3,
                'name' => 'Francesca Esposito',
                'number' => '+39 333 908 1122',
                'channel' => 'whatsapp',
                'insta_id' => 'francesca.esposito',
                'fb_id' => 'francesca.esposito',
            ],
            'contact_id_4' => [
                'id' => 4,
                'name' => 'Lorenzo Romano',
                'number' => '+39 349 771 2200',
                'channel' => 'whatsapp',
                'insta_id' => 'lorenzo.romano',
                'fb_id' => 'lorenzo.romano',
            ],
            'contact_id_5' => [
                'id' => 5,
                'name' => 'Chiara Conti',
                'number' => '+39 351 444 6677',
                'channel' => 'whatsapp',
                'insta_id' => 'chiara_conti',
                'fb_id' => 'chiara.conti',
            ],
            'contact_id_6' => [
                'id' => 6,
                'name' => 'Alessandro Greco',
                'number' => '+39 340 902 3344',
                'channel' => 'whatsapp',
                'insta_id' => 'alessandro.greco',
                'fb_id' => 'alessandro.greco',
            ],
            'contact_id_7' => [
                'id' => 7,
                'name' => 'Sara Colombo',
                'number' => '+39 388 120 7788',
                'channel' => 'whatsapp',
                'insta_id' => 'sara.colombo',
                'fb_id' => 'sara.colombo',
            ],
            'contact_id_8' => [
                'id' => 8,
                'name' => 'Davide De Luca',
                'number' => '+39 331 607 0909',
                'channel' => 'whatsapp',
                'insta_id' => 'davide.deluca',
                'fb_id' => 'davide.deluca',
            ],
            'contact_id_9' => [
                'id' => 9,
                'name' => 'Martina Ferri',
                'number' => '+39 392 321 4455',
                'channel' => 'whatsapp',
                'insta_id' => 'martina.ferri',
                'fb_id' => 'martina.ferri',
            ],
            'contact_id_10' => [
                'id' => 10,
                'name' => 'Antonio Ricci',
                'number' => '+39 366 909 0101',
                'channel' => 'whatsapp',
                'insta_id' => 'antonio.ricci',
                'fb_id' => 'antonio.ricci',
            ],
            'contact_id_11' => [
                'id' => 11,
                'name' => 'Elena Moretti',
                'number' => '+39 328 777 3300',
                'channel' => 'whatsapp',
                'insta_id' => 'elena.moretti',
                'fb_id' => 'elena.moretti',
            ],
            'contact_id_12' => [
                'id' => 12,
                'name' => 'Matteo Gallo',
                'number' => '+39 345 808 1212',
                'channel' => 'whatsapp',
                'insta_id' => 'matteo.gallo',
                'fb_id' => 'matteo.gallo',
            ],
            'contact_id_13' => [
                'id' => 13,
                'name' => 'Federico Rinaldi',
                'number' => '+39 327 614 8821',
                'channel' => 'whatsapp',
                'insta_id' => 'federico.rinaldi',
                'fb_id' => 'federico.rinaldi',
            ],
            'contact_id_14' => [
                'id' => 14,
                'name' => 'Valentina Russo',
                'number' => '+39 339 480 1120',
                'channel' => 'whatsapp',
                'insta_id' => 'valentina.russo',
                'fb_id' => 'valentina.russo',
            ],
            'contact_id_15' => [
                'id' => 15,
                'name' => 'Giorgio Pellegrini',
                'number' => '+39 346 901 7733',
                'channel' => 'whatsapp',
                'insta_id' => 'giorgio.pellegrini',
                'fb_id' => 'giorgio.pellegrini',
            ],
            'contact_id_16' => [
                'id' => 16,
                'name' => 'Ilaria Fontana',
                'number' => '+39 350 266 9087',
                'channel' => 'whatsapp',
                'insta_id' => 'ilaria.fontana',
                'fb_id' => 'ilaria.fontana',
            ],
            'contact_id_17' => [
                'id' => 17,
                'name' => 'Riccardo Sanna',
                'number' => '+39 334 712 0094',
                'channel' => 'whatsapp',
                'insta_id' => 'riccardo.sanna',
                'fb_id' => 'riccardo.sanna',
            ],
            'contact_id_18' => [
                'id' => 18,
                'name' => 'Serena Marchetti',
                'number' => '+39 389 552 4106',
                'channel' => 'whatsapp',
                'insta_id' => 'serena.marchetti',
                'fb_id' => 'serena.marchetti',
            ],
            'contact_id_19' => [
                'id' => 19,
                'name' => 'Nicola Barbieri',
                'number' => '+39 373 118 6602',
                'channel' => 'whatsapp',
                'insta_id' => 'nicola.barbieri',
                'fb_id' => 'nicola.barbieri',
            ],
            'contact_id_20' => [
                'id' => 20,
                'name' => 'Paola Neri',
                'number' => '+39 348 705 9911',
                'channel' => 'whatsapp',
                'insta_id' => 'paola.neri',
                'fb_id' => 'paola.neri',
            ],
            'contact_id_21' => [
                'id' => 21,
                'name' => 'Luca De Santis',
                'number' => '+39 320 111 0001',
                'channel' => 'whatsapp',
                'insta_id' => 'luca.desantis',
                'fb_id' => 'luca.desantis',
            ],
            'contact_id_22' => [
                'id' => 22,
                'name' => 'Martina Costa',
                'number' => '+39 320 111 0002',
                'channel' => 'whatsapp',
                'insta_id' => 'martina.costa',
                'fb_id' => 'martina.costa',
            ],
            'contact_id_23' => [
                'id' => 23,
                'name' => 'Andrea Lombardi',
                'number' => '+39 320 111 0003',
                'channel' => 'whatsapp',
                'insta_id' => 'andrea.lombardi',
                'fb_id' => 'andrea.lombardi',
            ],
            'contact_id_24' => [
                'id' => 24,
                'name' => 'Silvia Bianchi',
                'number' => '+39 320 111 0004',
                'channel' => 'whatsapp',
                'insta_id' => 'silvia.bianchi',
                'fb_id' => 'silvia.bianchi',
            ],
            'contact_id_25' => [
                'id' => 25,
                'name' => 'Davide Ferraro',
                'number' => '+39 320 111 0005',
                'channel' => 'whatsapp',
                'insta_id' => 'davide.ferraro',
                'fb_id' => 'davide.ferraro',
            ],
            'contact_id_26' => [
                'id' => 26,
                'name' => 'Gianna Vitale',
                'number' => '+39 320 111 0006',
                'channel' => 'whatsapp',
                'insta_id' => 'gianna.vitale',
                'fb_id' => 'gianna.vitale',
            ],
            'contact_id_27' => [
                'id' => 27,
                'name' => 'Matteo Riva',
                'number' => '+39 320 111 0007',
                'channel' => 'whatsapp',
                'insta_id' => 'matteo.riva',
                'fb_id' => 'matteo.riva',
            ],
            'contact_id_28' => [
                'id' => 28,
                'name' => 'Alessia Romano',
                'number' => '+39 320 111 0008',
                'channel' => 'whatsapp',
                'insta_id' => 'alessia.romano',
                'fb_id' => 'alessia.romano',
            ],
            'contact_id_29' => [
                'id' => 29,
                'name' => 'Paolo Greco',
                'number' => '+39 320 111 0009',
                'channel' => 'whatsapp',
                'insta_id' => 'paolo.greco',
                'fb_id' => 'paolo.greco',
            ],
            'contact_id_30' => [
                'id' => 30,
                'name' => 'Chiara Marino',
                'number' => '+39 320 111 0010',
                'channel' => 'whatsapp',
                'insta_id' => 'chiara.marino',
                'fb_id' => 'chiara.marino',
            ],
            'contact_id_31' => [
                'id' => 31,
                'name' => 'Stefano Conti',
                'number' => '+39 320 111 0011',
                'channel' => 'whatsapp',
                'insta_id' => 'stefano.conti',
                'fb_id' => 'stefano.conti',
            ],
            'contact_id_32' => [
                'id' => 32,
                'name' => 'Elisa Piras',
                'number' => '+39 320 111 0012',
                'channel' => 'whatsapp',
                'insta_id' => 'elisa.piras',
                'fb_id' => 'elisa.piras',
            ],
            'contact_id_33' => [
                'id' => 33,
                'name' => 'Marco Serra',
                'number' => '+39 320 111 0013',
                'channel' => 'whatsapp',
                'insta_id' => 'marco.serra',
                'fb_id' => 'marco.serra',
            ],
            'contact_id_34' => [
                'id' => 34,
                'name' => 'Francesca Rizzo',
                'number' => '+39 320 111 0014',
                'channel' => 'whatsapp',
                'insta_id' => 'francesca.rizzo',
                'fb_id' => 'francesca.rizzo',
            ],
            'contact_id_35' => [
                'id' => 35,
                'name' => 'Alberto Ricci',
                'number' => '+39 320 111 0015',
                'channel' => 'whatsapp',
                'insta_id' => 'alberto.ricci',
                'fb_id' => 'alberto.ricci',
            ],
            'contact_id_36' => [
                'id' => 36,
                'name' => 'Aurora Moretti',
                'number' => '+39 320 111 0016',
                'channel' => 'whatsapp',
                'insta_id' => 'aurora.moretti',
                'fb_id' => 'aurora.moretti',
            ],
            'contact_id_37' => [
                'id' => 37,
                'name' => 'Gabriele Mancini',
                'number' => '+39 320 111 0017',
                'channel' => 'whatsapp',
                'insta_id' => 'gabriele.mancini',
                'fb_id' => 'gabriele.mancini',
            ],
            'contact_id_38' => [
                'id' => 38,
                'name' => 'Laura Gatti',
                'number' => '+39 320 111 0018',
                'channel' => 'whatsapp',
                'insta_id' => 'laura.gatti',
                'fb_id' => 'laura.gatti',
            ],
            'contact_id_39' => [
                'id' => 39,
                'name' => 'Simone Colombo',
                'number' => '+39 320 111 0019',
                'channel' => 'whatsapp',
                'insta_id' => 'simone.colombo',
                'fb_id' => 'simone.colombo',
            ],
            'contact_id_40' => [
                'id' => 40,
                'name' => 'Beatrice Romano',
                'number' => '+39 320 111 0020',
                'channel' => 'whatsapp',
                'insta_id' => 'beatrice.romano',
                'fb_id' => 'beatrice.romano',
            ],
            'contact_id_41' => [
                'id' => 41,
                'name' => 'Pietro Bassi',
                'number' => '+39 320 111 0021',
                'channel' => 'whatsapp',
                'insta_id' => 'pietro.bassi',
                'fb_id' => 'pietro.bassi',
            ],
            'contact_id_42' => [
                'id' => 42,
                'name' => 'Sara Giordano',
                'number' => '+39 320 111 0022',
                'channel' => 'whatsapp',
                'insta_id' => 'sara.giordano',
                'fb_id' => 'sara.giordano',
            ],
            'contact_id_43' => [
                'id' => 43,
                'name' => 'Tommaso Conti',
                'number' => '+39 320 111 0023',
                'channel' => 'whatsapp',
                'insta_id' => 'tommaso.conti',
                'fb_id' => 'tommaso.conti',
            ],
            'contact_id_44' => [
                'id' => 44,
                'name' => 'Martina Sanna',
                'number' => '+39 320 111 0024',
                'channel' => 'whatsapp',
                'insta_id' => 'martina.sanna',
                'fb_id' => 'martina.sanna',
            ],
            'contact_id_45' => [
                'id' => 45,
                'name' => 'Lorenzo De Luca',
                'number' => '+39 320 111 0025',
                'channel' => 'whatsapp',
                'insta_id' => 'lorenzo.deluca',
                'fb_id' => 'lorenzo.deluca',
            ],
            'contact_id_46' => [
                'id' => 46,
                'name' => 'Federica Bruno',
                'number' => '+39 320 111 0026',
                'channel' => 'whatsapp',
                'insta_id' => 'federica.bruno',
                'fb_id' => 'federica.bruno',
            ],
            'contact_id_47' => [
                'id' => 47,
                'name' => 'Roberto Rinaldi',
                'number' => '+39 320 111 0027',
                'channel' => 'whatsapp',
                'insta_id' => 'roberto.rinaldi',
                'fb_id' => 'roberto.rinaldi',
            ],
            'contact_id_48' => [
                'id' => 48,
                'name' => 'Claudia Ferri',
                'number' => '+39 320 111 0028',
                'channel' => 'whatsapp',
                'insta_id' => 'claudia.ferri',
                'fb_id' => 'claudia.ferri',
            ],
            'contact_id_49' => [
                'id' => 49,
                'name' => 'Michele Barbieri',
                'number' => '+39 320 111 0029',
                'channel' => 'whatsapp',
                'insta_id' => 'michele.barbieri',
                'fb_id' => 'michele.barbieri',
            ],
            'contact_id_50' => [
                'id' => 50,
                'name' => 'Valeria Russo',
                'number' => '+39 320 111 0030',
                'channel' => 'whatsapp',
                'insta_id' => 'valeria.russo',
                'fb_id' => 'valeria.russo',
            ],
            'contact_id_51' => [
                'id' => 51,
                'name' => 'Alessandro Vitale',
                'number' => '+39 320 111 0031',
                'channel' => 'whatsapp',
                'insta_id' => 'alessandro.vitale',
                'fb_id' => 'alessandro.vitale',
            ],
            'contact_id_52' => [
                'id' => 52,
                'name' => 'Camilla Esposito',
                'number' => '+39 320 111 0032',
                'channel' => 'instagram',
                'insta_id' => 'camilla.esposito',
                'fb_id' => 'camilla.esposito',
            ],
            'contact_id_53' => [
                'id' => 53,
                'name' => 'Giacomo Costa',
                'number' => '+39 320 111 0033',
                'channel' => 'instagram',
                'insta_id' => 'giacomo.costa',
                'fb_id' => 'giacomo.costa',
            ],
            'contact_id_54' => [
                'id' => 54,
                'name' => 'Noemi Greco',
                'number' => '+39 320 111 0034',
                'channel' => 'instagram',
                'insta_id' => 'noemi.greco',
                'fb_id' => 'noemi.greco',
            ],
            'contact_id_55' => [
                'id' => 55,
                'name' => 'Emanuele Gallo',
                'number' => '+39 320 111 0035',
                'channel' => 'instagram',
                'insta_id' => 'emanuele.gallo',
                'fb_id' => 'emanuele.gallo',
            ],
            'contact_id_56' => [
                'id' => 56,
                'name' => 'Lucia Neri',
                'number' => '+39 320 111 0036',
                'channel' => 'instagram',
                'insta_id' => 'lucia.neri',
                'fb_id' => 'lucia.neri',
            ],
            'contact_id_57' => [
                'id' => 57,
                'name' => 'Matteo Orsi',
                'number' => '+39 320 111 0037',
                'channel' => 'facebook',
                'insta_id' => 'matteo.orsi',
                'fb_id' => 'matteo.orsi',
            ],
            'contact_id_58' => [
                'id' => 58,
                'name' => 'Sofia Pellegrini',
                'number' => '+39 320 111 0038',
                'channel' => 'facebook',
                'insta_id' => 'sofia.pellegrini',
                'fb_id' => 'sofia.pellegrini',
            ],
            'contact_id_59' => [
                'id' => 59,
                'name' => 'Riccardo Romano',
                'number' => '+39 320 111 0039',
                'channel' => 'facebook',
                'insta_id' => 'riccardo.romano',
                'fb_id' => 'riccardo.romano',
            ],
            'contact_id_60' => [
                'id' => 60,
                'name' => 'Elisa Ricci',
                'number' => '+39 320 111 0040',
                'channel' => 'facebook',
                'insta_id' => 'elisa.ricci',
                'fb_id' => 'elisa.ricci',
            ],
        ];
    }

    public static function sessionMap(): array
    {
        return [
            1 => [1 => true],
            2 => [1 => true],
            3 => [1 => true],
            4 => [1 => true],
            5 => [1 => true],
            6 => [1 => true],
            7 => [1 => true],
            8 => [1 => true],
            9 => [1 => true],
            10 => [1 => true],
            11 => [1 => true],
            12 => [1 => true],
            13 => [1 => true],
            14 => [1 => true],
            15 => [1 => true],
            16 => [1 => true],
            17 => [1 => true],
            18 => [1 => true],
            19 => [1 => true],
            20 => [1 => true],
        ];
    }

    public static function templates(): array
    {
        return [
            [
                'id' => 1,
                'template_uid' => 'mock_template_1',
                'account_id' => 1,
                'name' => 'Richiesta documenti prestito',
                'channel' => 'whatsapp',
                'body' => "Ciao {nome}, per avviare la richiesta di prestito mi servono: documento d'identita, codice fiscale e ultima busta paga. Quando puoi inviarmeli?",
            ],
            [
                'id' => 2,
                'template_uid' => 'mock_template_2',
                'account_id' => 1,
                'name' => 'Esito pre-valutazione',
                'channel' => 'whatsapp',
                'body' => 'Ciao {nome}, dalla pre-valutazione risulta un importo indicativo fino a {importo} EUR con durata {durata} mesi. Vuoi che proceda con la pratica?',
            ],
            [
                'id' => 3,
                'template_uid' => 'mock_template_3',
                'account_id' => 1,
                'name' => 'Promemoria firma contratto',
                'channel' => 'whatsapp',
                'body' => 'Ciao {nome}, ti ricordo che per finalizzare il prestito serve la firma del contratto. Ti va bene fissare oggi alle {ora}?',
            ],
        ];
    }

    public static function products(): array
    {
        return [
            [
                'id' => 'loan_personal',
                'name' => 'Prestito Personale',
                'min_amount' => 1000,
                'max_amount' => 30000,
                'min_months' => 12,
                'max_months' => 84,
                'catalog_id' => 'catalog_loan_personal',
                'retailer_id' => 'retailer_loan_personal',
            ],
            [
                'id' => 'loan_consolidation',
                'name' => 'Consolidamento Debiti',
                'min_amount' => 3000,
                'max_amount' => 50000,
                'min_months' => 24,
                'max_months' => 120,
                'catalog_id' => 'catalog_loan_consolidation',
                'retailer_id' => 'retailer_loan_consolidation',
            ],
            [
                'id' => 'loan_salary_backed',
                'name' => 'Cessione del Quinto',
                'min_amount' => 5000,
                'max_amount' => 60000,
                'min_months' => 24,
                'max_months' => 120,
                'catalog_id' => 'catalog_loan_salary_backed',
                'retailer_id' => 'retailer_loan_salary_backed',
            ],
        ];
    }

    public static function interactiveMessages(): array
    {
        return [
            [
                'id' => 'im_1',
                'name' => 'Che tipo di prestito ti interessa?',
                'option_type' => 'quick_replies',
                'content' => 'Che tipo di prestito ti interessa?',
                'options' => [
                    'Prestito personale',
                    'Consolidamento debiti',
                    'Cessione del quinto',
                ],
            ],
            [
                'id' => 'im_2',
                'name' => 'Importo richiesto',
                'option_type' => 'quick_replies',
                'content' => 'Importo richiesto',
                'options' => ['5.000 EUR', '10.000 EUR', '20.000 EUR', 'Altro'],
            ],
            [
                'id' => 'im_3',
                'name' => 'Durata preferita',
                'option_type' => 'quick_replies',
                'content' => 'Durata preferita',
                'options' => ['24 mesi', '48 mesi', '72 mesi', 'Non so'],
            ],
        ];
    }

    public static function mockMessages(): array
    {
        return [
            1 => [
                [
                    'id' => 101,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, mi servirebbe un prestito personale da 8.000 EUR.',
                    'date' => '2026-02-15 08:55',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 102,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao Giulia! Certo. Hai gia in mente durata (24/48/72 mesi) e finalita? Cosi ti preparo una simulazione.',
                    'date' => '2026-02-15 08:58',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 103,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Direi 48 mesi, serve per spese casa.',
                    'date' => '2026-02-15 09:02',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 104,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Perfetto. Per avviare la richiesta mi invii documento, CF e ultima busta paga? Poi ti mando il preventivo.',
                    'date' => '2026-02-15 09:06',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            2 => [
                [
                    'id' => 201,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Buonasera, vorrei sapere se posso ottenere 15.000 EUR.',
                    'date' => '2026-02-15 18:12',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 202,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao Marco! Si, possiamo fare una pre-valutazione. Che lavoro fai e che durata preferisci (36/48/60 mesi)?',
                    'date' => '2026-02-15 18:15',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 203,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Dipendente, preferirei 60 mesi. Ho un altro prestito in corso.',
                    'date' => '2026-02-15 18:35',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            3 => [
                [
                    'id' => 301,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, mi interessa un prestito da 10.000 EUR ma non so la durata.',
                    'date' => '2026-02-14 15:40',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 302,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao Francesca! Nessun problema: preferisci una rata piu bassa (durata lunga) o chiudere prima (durata breve)?',
                    'date' => '2026-02-14 15:43',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 303,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Meglio rata piu bassa, magari 72 mesi.',
                    'date' => '2026-02-14 15:55',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            4 => [
                [
                    'id' => 401,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Salve, ho inviato i documenti ieri. Ci sono aggiornamenti sulla pratica?',
                    'date' => '2026-02-13 10:50',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 402,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => "Ciao Lorenzo! Si, la pratica e in verifica. Appena ho l'esito ti aggiorno subito qui.",
                    'date' => '2026-02-13 11:30',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            5 => [
                [
                    'id' => 501,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, ho 2 prestiti e la rata e alta. Si puo consolidare?',
                    'date' => '2026-02-15 12:58',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 502,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao Chiara! Si, il consolidamento serve proprio a unire i debiti e ridurre la rata. Mi mandi importi residui e rate attuali?',
                    'date' => '2026-02-15 13:05',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 503,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Residuo 6.200 EUR (rata 210 EUR) e 9.800 EUR (rata 295 EUR).',
                    'date' => '2026-02-15 13:18',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            6 => [
                [
                    'id' => 601,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Buongiorno, cessione del quinto per pensione: e possibile?',
                    'date' => '2026-02-12 09:10',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            7 => [
                [
                    'id' => 701,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, posso avere info su un prestito veloce 5.000 EUR?',
                    'date' => '2026-02-11 17:42',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            8 => [
                [
                    'id' => 801,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Vorrei un preventivo per 20.000 EUR in 60 mesi.',
                    'date' => '2026-02-10 12:20',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            9 => [
                [
                    'id' => 901,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, mi serve liquidita per auto: 12.000 EUR.',
                    'date' => '2026-02-09 09:30',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            10 => [
                [
                    'id' => 1001,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Salve, ho avuto un rifiuto altrove. Posso riprovare con voi?',
                    'date' => '2026-02-08 16:10',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            11 => [
                [
                    'id' => 1101,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, posso estinguere anticipatamente senza penali?',
                    'date' => '2026-02-07 11:05',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            12 => [
                [
                    'id' => 1201,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => "Buongiorno, quanto tempo ci vuole per l'erogazione?",
                    'date' => '2026-02-06 08:40',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            13 => [
                [
                    'id' => 1301,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, mi interessa un prestito da 6.000 EUR. Che documenti servono?',
                    'date' => '2026-02-15 10:12',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            14 => [
                [
                    'id' => 1401,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, posso avere una rata indicativa per 12.000 EUR in 60 mesi?',
                    'date' => '2026-02-15 11:58',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            15 => [
                [
                    'id' => 1501,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Buonasera, ho un prestito e una carta revolving. Posso consolidare tutto insieme?',
                    'date' => '2026-02-14 19:33',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 1502,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao Giorgio! Si, spesso si puo includere anche la revolving. Mi mandi importo residuo e rate attuali? Ti preparo una proposta unica.',
                    'date' => '2026-02-14 19:42',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            16 => [
                [
                    'id' => 1601,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, ho inviato busta paga e documento. Confermi ricezione?',
                    'date' => '2026-02-15 16:20',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 0,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            17 => [
                [
                    'id' => 1701,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, sono dipendente pubblico. Posso fare la cessione del quinto?',
                    'date' => '2026-02-12 17:22',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
                [
                    'id' => 1702,
                    'mode' => 'outgoing',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => "Ciao Riccardo! Si, e possibile. Mi invii ultima busta paga e documento? Dimmi anche l'importo desiderato e la durata.",
                    'date' => '2026-02-12 17:35',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            18 => [
                [
                    'id' => 1801,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => "Ciao, dopo la firma quanto tempo passa per l'erogazione?",
                    'date' => '2026-02-15 09:44',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            19 => [
                [
                    'id' => 1901,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => "Ciao, se estinguo prima il prestito c'e una penale?",
                    'date' => '2026-02-13 08:12',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
            20 => [
                [
                    'id' => 2001,
                    'mode' => 'incoming',
                    'type' => 'text',
                    'category' => 'whatsapp',
                    'content' => 'Ciao, sto valutando 5.000 EUR. E possibile anche senza busta paga?',
                    'date' => '2026-02-14 09:05',
                    'status' => 'Delivered',
                    'delivered' => 1,
                    'read' => 1,
                    'path' => null,
                    'error' => null,
                    'is_reply' => false,
                    'is_mention' => false,
                ],
            ],
        ];
    }
}
